### ISSUE TITLE
Integracja z API Facebooka

### ISSUE THREAD

**Issue by 0xuser** [0xuser/Mapa-Stancji#11]
Logowanie za pośrednictwem Facebook'a.
Pobieranie znajomych, adresu profilówki.

**Comment by ilinoyer** [comment]
Proponuje przedłużyć do 15.04

**Comment by wojciech-jakub** [comment]
Nie widzę  przeciwwskazań

**Comment by ilinoyer** [comment]
Prace zawieszone do momentu stworzenia pełnej możliwości dodawania ogłoszeń. 
W wolnym czasie osoby chętne mogą się rozeznać w temacie API FB.

@wojciech-jakub  @drakian003  ?

**Comment by wojciech-jakub** [comment]
Ja mogę poszukać i poczytać.

**Comment by wojciech-jakub** [comment]
https://restfb.com/
https://developers.facebook.com/docs/facebook-login/

**Comment by mkabionek** [comment]
Jakieś postępy? 
@wojciech-jakub @drakian003

**Comment by wojciech-jakub** [comment]
udało mi sie nawiazac połączenie. wieczorem dalej bede nad tym pracowac. 
![image](https://user-images.githubusercontent.com/33074084/40842778-3efd0cd6-65af-11e8-8ebc-16096fd1b056.png)

**Comment by wojciech-jakub** [comment]
Zarejestrowalem apke na fb. Dziala mi logowanie. Mam drobne problemy z dodawaniem użytkowników do bazy
