### ISSUE TITLE
Mini mapa do wyboru lokalizacji przy formularzu dodawania ogłoszenia

### ISSUE THREAD

**Issue by 0xuser** [0xuser/Mapa-Stancji#14]
Mapa google o wymiarze 600x400 pikseli, wyśrodkowana na centrum Krakowa.
Użytkownik ma mieć możliwość dodania jednej pinezki.

Współrzędne pinezki muszą "dać" pobrać swoje współrzędne. Dane te będą przekazywane przez formularz do bazy danych

**Comment by ilinoyer** [comment]
Jakies postepy w tej sprawie ?

**Comment by 0xuser** [comment]
![image](https://user-images.githubusercontent.com/17354026/40145072-cb700a84-5960-11e8-8676-49e7a165faa4.png)

Mam zrobione. Mapka centruje się na centrum Krakowa (50.06164150725729, 19.937772750854492)
Marker można przesuwać kursorem, pobieram jego dł. i szer. geograficzna oraz najbliższy adres.

**Comment by wojciech-jakub** [comment]
Jeżeli chodzi o to w Js tez to mam zrobione. Jeżeli piszemy  w react to taak nie jest zamknięty bo to jest czysty js
