### ISSUE TITLE
Endpoint udostępniający listę przystanków i uczelni

### ISSUE THREAD

**Issue by mkabionek** [0xuser/Mapa-Stancji#17]
Założenia:
 - Możliwość pobrania listy przystanków
 - możliwość pobrania listy uczelni

```
{
  stops: [
    {
      id: 1,
      name: 'Politechnika',
      coord: {
        lat: 30.000,
        lon: 100.000
      }
    }
  ],
  academies: [
    {
      id: 1,
      name: 'Politechnika Krakowska',
      coord: {
        lat: 30.000,
        lon: 100.000
      }
    }
  ]
}
```

**Comment by ilinoyer** [comment]
@0xuser 

Czyli ostatecznie jak rozumiem ma się pojawić nowa tabela w naszej bazie która będzie zawierała te informacje ?

Jeżeli tak kto ma się tym zająć oraz skąd pobrać te dane ?

**Comment by ilinoyer** [comment]
@0xuser ping

**Comment by ilinoyer** [comment]
@0xuser ping

**Comment by 0xuser** [comment]
Zgadza się. Jeśli nie ma tabeli zrobię ją.

**Comment by ilinoyer** [comment]
Problem nie będzie większy z zebraniem danych ?
Da się coś takiego wyciągnać z google maps ?

**Comment by 0xuser** [comment]
Tabela "Marker" stworzona
![image](https://user-images.githubusercontent.com/17354026/40332327-085fb95c-5d54-11e8-9427-90add0594209.png)
dla uproszczenia IdType może być zwyczajnie nazwą pliku graficznego (np. przystanek id:1 obrazek do wyswietlenia img/.../1.png)

@ilinoyer 
Nie wiem jak wygląda to od strony Api Google maps. Nam raczej chodzi o prostą implementacje wyświetlania predefiniowanych markerów w celach "prezentacyjnych". Na mapę ręcznie zostaną naniesione uczelnie, ewentualnie parę przystanków dla przykładu. 

Na tym etapie bez żadnego systemu dodawania, usuwania - zwykłe wyświetlanie markerów o określonych grafikach z bazy.

Możliwości są duże ale jesteśmy ograniczeni czasowo* 

_ciekawostka: API jakdojade pozwalałoby nam nawet na wyświetlanie rozkładu po kliknięciu w marker przystanku._

**Comment by ilinoyer** [comment]
Chodziło mi bardziej o to czym zapełniły tą tabelkę xD

**Comment by 0xuser** [comment]
@ilinoyer 
wrzucę jutro kilkanaście rekordów

**Comment by 0xuser** [comment]
@ilinoyer 
https://github.com/0xuser/Mapa-Stancji/issues/26

**Comment by ilinoyer** [comment]
Na razie to wszystko w tym temacie. Zamykam
