### ISSUE TITLE
Stworzenie większej ilości danych testowych

### ISSUE THREAD

**Issue by ilinoyer** [0xuser/Mapa-Stancji#18]
Wydaje mi się, że przydało by się troche zapełnić bazę. Szukam chętnego który to zrobi. 
Wymaganie jest takie, że najlepiej, żeby to było w SQLu gdyż w razie gdy wyczyścimy baze będzie można użyć tego samego zamiast klepać od nowa.

**Comment by 0xuser** [comment]
Zajmę się tym dzisiaj. Nie jest potrzebne pisanie INSERTÓW, wystarczy później importować bazę.

**Comment by ilinoyer** [comment]
A jak ktoś dropnie bazę przez przypadek ?

**Comment by ilinoyer** [comment]
Danych dosyć. Zostajemy przy jednej bazie.
