### ISSUE TITLE
Problem z kilkoma ogłoszeniami w jednym miejscu 

### ISSUE THREAD

**Issue by ilinoyer** [0xuser/Mapa-Stancji#20]
Gdy dodam ogłoszenie w tym samym budynku na mapie pokazuje się :
![image](https://user-images.githubusercontent.com/25120671/40142846-1b019e7a-595a-11e8-81ce-dea3228dc6d0.png)

Proponuje wyświetlać wtedy jeden znacznik, a po kliknięciu pokazywac 2 oferty. 
@mkabionek do zrobienia ?

**Comment by mkabionek** [comment]
Błąd wynikał z błędu w bazie. Pozostaje kwestia wyświetlenia kilku ofert po kliknięciu w znacznik.

**Comment by ilinoyer** [comment]
Bug rozwiązany. Prace nad rozwiązaniem problemu z wyświetlaniem kilku ogłoszeń w tym samym miejscu prowadzone w #25
