### ISSUE TITLE
Modyfikacja bazy danych

### ISSUE THREAD

**Issue by mkabionek** [0xuser/Mapa-Stancji#21]
Musimy trochę przerobić bazę danych żeby przechowywać użytkowników zwykłych i tych facebookowych. Może się ktoś tym zająć?

![zrzut ekranu 2018-05-19 o 22 50 37](https://user-images.githubusercontent.com/11436660/40272976-1c431d94-5bb8-11e8-9463-9d0c99d07767.png)

**Comment by ilinoyer** [comment]
+ do user profile dodanie numeru telefonu

**Comment by ilinoyer** [comment]
Do bazy zostały dodane 2 tabele. W przyszłości będzie potrzebna zmiana : dodanie do użytkownika Facebookowego adresu. 
![image](https://user-images.githubusercontent.com/25120671/40386906-51a6d6a6-5e0b-11e8-9aad-02af94d219b7.png)
