### ISSUE TITLE
Weryfikacja bazy danych

### ISSUE THREAD

**Issue by ilinoyer** [0xuser/Mapa-Stancji#5]
Baza danych została stworzona zgodnie z założeniami. 
Proszę o sprawdzenie i ewentualne uwagi.

@drakian003 
@wojciech-jakub

**Comment by ilinoyer** [comment]
@drakian003 @wojciech-jakub 
Rozumiem, że póki co wszystko jest ok ? 
Jeżeli tak to proszę o zamknięcie @0xuser

**Comment by wojciech-jakub** [comment]
moim zdaniem jest ok, zamykam
